import { useState , useEffect } from "react";

 function RandomIndexGenerator(i){
    return Math.floor(Math.random() * i);
}
export  function ImagesUrls () {

return(<><img src="/images/background-img.jpg" alt="web-img" style={{height:"300px",width:"100%",aspectRatio:"3",objectFit:"cover"}} /></>);
}
export  function Qoutes(){
    const studyQuotes = [
  "Education is the key that unlocks the doors of opportunity.",
  "Study hard, for knowledge is a treasure that follows its owner everywhere.",
  "Learning never exhausts the mind.",
  "The future belongs to those who prepare for it today.",
  "Success is no accident; it is hard work and learning.",
  "Dream big, study harder, and make it happen.",
  "Knowledge is power, and learning is the path to it.",
  "The roots of education are bitter, but the fruit is sweet.",
  "Study like there’s no tomorrow because tomorrow you might be living your dreams.",
  "An investment in knowledge always pays the best interest.",
  "Don’t wish for it, work for it.",
  "Education is the most powerful weapon you can use to change the world.",
  "The expert in anything was once a beginner.",
  "Success comes to those who are too busy to be looking for it.",
  "Discipline is the bridge between goals and achievement.",
  "Study now, shine later.",
  "Learning is not attained by chance; it must be sought with ardor.",
  "Education is not preparation for life; education is life itself.",
  "Knowledge is the foundation of every great achievement.",
  "Learning gives you wings to fly.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Education is the passport to the future.",
  "Push yourself, because no one else is going to do it for you.",
  "Don’t stop when you’re tired, stop when you’re done.",
  "Study because greatness requires preparation.",
  "If you can dream it, you can achieve it through learning.",
  "Knowledge has no limit; keep going.",
  "Learning is the eye of the mind.",
  "Books are the quietest and most constant of friends.",
  "Study like a scholar, act like a leader.",
  "Today’s studying builds tomorrow’s success.",
  "Your education is your superpower.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Great minds are shaped by great learning habits.",
  "Study is the seed; success is the fruit.",
  "There is no substitute for hard study.",
  "A day spent learning is a day invested, not wasted.",
  "Study is not about time, it’s about commitment.",
  "Learning is a journey, not a race.",
  "Small steps in study lead to giant leaps in success.",
  "Education turns dreams into reality.",
  "To learn is to grow.",
  "The greatest wealth is knowledge.",
  "Learning is a light that never dims.",
  "The more you learn, the more you earn.",
  "Effort in study builds strength in character.",
  "Greatness is achieved through relentless learning.",
  "One book, one pen, one student can change the world.",
  "Study until your idols become your rivals.",
  "Learning is the beginning of wisdom.",
  "There’s no elevator to success; you have to take the stairs of study.",
  "Education is the foundation of freedom.",
  "Focus on progress, not perfection.",
  "Learning is the only thing the mind never exhausts or fears.",
  "Study creates confidence, confidence creates success.",
  "With knowledge comes power and purpose.",
  "Learning is the path to greatness.",
  "A mind stretched by new learning never returns to its old size.",
  "Study sharpens the mind like a sword.",
  "The best preparation for tomorrow is learning today.",
  "Learning is like climbing a mountain; every step counts.",
  "Excellence begins with study.",
  "There’s beauty in the process of learning.",
  "Learning is your weapon, use it wisely.",
  "Knowledge is a treasure; study is the key.",
  "Dare to study, dare to succeed.",
  "Hard study creates soft landings.",
  "The key to success is hidden in daily learning.",
  "Study gives strength to your dreams.",
  "The greatest investment is in your mind.",
  "Work hard in silence, let your knowledge roar.",
  "Study is the engine of progress.",
  "Every page you read is a step closer to your dream.",
  "Study with purpose, achieve with pride.",
  "The best view comes after the hardest climb.",
  "Learn deeply, achieve greatly.",
  "Success loves preparation.",
  "The road to greatness is paved with learning.",
  "Great minds never stop learning.",
  "Learning is the heart of growth.",
  "Study builds the bridge between now and your future.",
  "Success begins in the classroom of discipline.",
  "Greatness starts with good study habits.",
  "To learn something new is to open a new door.",
  "Reading is dreaming with your eyes open.",
  "Knowledge turns obstacles into opportunities.",
  "Education doesn’t just change your life, it changes generations.",
  "The more you study, the more luck you have.",
  "Study is the armor of the wise.",
  "Learning empowers, excuses weaken.",
  "A curious mind is a learning mind.",
  "Study with passion or not at all.",
  "Every hour spent studying is an hour invested in your future.",
  "Learning is the seed of innovation.",
  "Knowledge builds leaders.",
  "The best way to predict your future is to study for it.",
  "Study is the stairway to success.",
  "Learning is endless, like the sky.",
  "Education is the door; effort is the key.",
  "Study relentlessly, succeed effortlessly.",
  "The foundation of greatness is learning."
];
const [qoute,setQoute] = useState(studyQuotes[RandomIndexGenerator(100)]);
    useEffect(()=>{
    setInterval(()=>{
        setQoute(studyQuotes[RandomIndexGenerator(100)]);
    },5e3);
    },[]);

 return qoute;
}